### ISSUE TITLE
profilehub.me related issue

### ISSUE THREAD

**Issue by KartikeSingh** [sell/sell#1]
## Problem
CSS issue in mobile mode
My screen width => 393 pixel

![Screenshot_2021-11-16-08-01-34-662_com android chrome](https://user-images.githubusercontent.com/67275060/141885267-cd787453-5283-422b-865a-b11390d3a887.jpg)

Anyways what's up

**Comment by sell** [comment]
Ahh, thanks for this. I did modify changes prior to going on vacation. I am going to rewrite the home page, to make it more profession and better looking.

**Comment by KartikeSingh** [comment]
okay :D
